### PR TITLE
Login screen

### PR DESCRIPTION
**Pull request by spaceofmiah**
## Description
This feature holds login component for login page created in react meant to address the issue #3

Fixes #(issue number 3) #3

## How Has This Been Tested?
Using `npm start` command launches the login page without throwing up any error or warning.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added necessary inline code documentation
- [ ] I have added tests that prove my fix is effective and that this feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by ajirimoses — DISMISSED** [review]

**Review by ezekieltech — CHANGES_REQUESTED** [review]
In the package.json file, we have "^1.2.1" in the dependencies section. Can we have them as "1.2.1". So if there's a (major, minor) change in the package between now and whenever anybody wants to check the project, the code will not fail.

Liaise with @Chukwuedo on the font standard. Essentially, you want to use Google fonts that can combine two styles so, for example, the headings and paragraphs will have different styles

**Comment by spaceofmiah** [comment]
The fonts utilized for the design is exact same fonts used for the prototype and yes it's google fonts.

https://github.com/BuildForSDG/Team-108-Frontend/blob/3c49ff07781420cc339066bc0a33e47817f695e0/index.css#L1

**Comment by Chukwuedo** [comment]
@spaceofmiah great work. I don't have further comments

**Review by Chukwuedo — APPROVED** [review]
No further comments

**Review by ezekieltech — APPROVED** [review]

**Review by Stephen-Kamau — APPROVED** [review]

**Pull request merged**
